default:
    @just --list

cp:
    fd -e go -x sh -c 'echo "===== {} ====="; cat {}; echo' | wl-copy

build:
    @go build -o hello main.go
    @echo "Build complete -> hello"

build-windows:
    @go build -ldflags="-H windowsgui" -o hello.exe main.go
    @echo "Build complete -> hello.exe"

pkg: build
    @mkdir -p hello-server/web hello-server/config
    @cp -r web/* hello-server/web/
    @cp config/config.yaml hello-server/config/
    @mv hello hello-server/
    @echo "Packaging complete -> ./hello-server"

pkg-windows: build-windows
    @mkdir -p hello-server/web/ hello-server/config/
    @cp -r web/* hello-server/web/
    @cp config/config.yaml hello-server/config/
    @mv hello.exe hello-server/
    @echo "Packaging complete -> ./hello-server"
